import NCC.Lower.Serialization
import NCC.Lower.ScaledMembership

/-!
# The current zero-respecting lower bound

The queried points are generated by the actual causal local-oracle model.
The fixed coordinate permutation, the actual scaled saddle zero-chain, and
the terminal OS obstruction are proved inputs from the current construction.
Neither sequential discovery nor a hard-instance certificate is assumed.
-/

namespace NCC.Lower.ZeroRespecting

noncomputable section

open NCCLowerBoundVerification NCC.Construction
open Certificates Parameters MoreauObstruction Serialization

theorem actual_scaled_field_zeroChain {m n : ℕ} (hn : 0 < n) (ell D eps : ℝ) :
    NCPLVerification.IsFirstOrderZeroChain
      (fieldOf (ScaledMembership.scaled (m := m) hn ell D eps).gradX
        (ScaledMembership.scaled (m := m) hn ell D eps).gradY) := by
  exact scaled_field_zeroChain hn (scale constants ell eps) (amplitude constants ell eps)

/-- The support induction concerns the gradients returned at the actual
recursively generated oracle queries. It holds at every time. -/
theorem queried_supportedBelow {m n : ℕ} (hn : 0 < n) (ell D eps : ℝ)
    {X : Set (Composite.Primal m)} {Y : Set (Composite.Dual m n)}
    (A : Oracle.DeterministicFOComponent X Y)
    (hzero : A.IsZeroRespectingOn (ScaledMembership.scaled hn ell D eps)) (t : ℕ) :
    NCPLVerification.SupportedBelow t
      (serialize (A.queriedAt (ScaledMembership.scaled hn ell D eps) t).1
        (A.queriedAt (ScaledMembership.scaled hn ell D eps) t).2) :=
  NCPLVerification.sequential_query_discovery (actual_scaled_field_zeroChain hn ell D eps)
    (queried_zeroRespecting A (ScaledMembership.scaled hn ell D eps) hzero) t

theorem terminal_position {m n : ℕ} (hm : 0 < m) :
    (sIndex n (⟨m - 1, by omega⟩ : Fin m)).val + 1 = m * (n + 3) := by
  change (m - 1) * (n + 3) + n + 2 + 1 = m * (n + 3)
  have hm' : m = (m - 1) + 1 := by omega
  conv_rhs => rw [hm']
  ring

/-- The terminal current state, not the last coordinate of the public
primal vector, remains zero for all `t < m*(n+3)`. -/
theorem queried_terminal_zero {m n : ℕ} (hm : 0 < m) (hn : 0 < n) (ell D eps : ℝ)
    {X : Set (Composite.Primal m)} {Y : Set (Composite.Dual m n)}
    (A : Oracle.DeterministicFOComponent X Y)
    (hzero : A.IsZeroRespectingOn (ScaledMembership.scaled hn ell D eps))
    {t : ℕ} (ht : t < m * (n + 3)) :
    (A.queriedAt (ScaledMembership.scaled hn ell D eps) t).1 (terminalIndex hm) = 0 := by
  have hs := queried_supportedBelow hn ell D eps A hzero t
  have hp := terminal_position (n := n) hm
  have hz := hs (sIndex n ⟨m - 1, by omega⟩) (by omega)
  rw [serialize_s] at hz
  exact hz

/-- Every matching zero-respecting causal component fails the true Moreau
OS test throughout the full discovery horizon. No regularity or terminal
certificate for the explicit objective is left as a hypothesis. -/
theorem hittingTimeAtLeast {m n : ℕ} (hm : 0 < m) (hn : 10 ≤ n)
    {ell D eps : ℝ} (hell : 0 < ell) (hD : 0 < D) (heps : 0 < eps)
    (hsize : (n : ℝ) ≤ constants.cD * (D / scale constants ell eps)) :
    Oracle.ZeroRespectingHittingTimeAtLeast
      (ScaledMembership.scaled (m := m) (by omega : 0 < n) ell D eps)
      ell eps (m * (n + 3)) := by
  intro X Y A _hmatch hzero t ht
  exact ScaledMembership.not_OS_at_terminal_zero hm hn hell hD heps hsize
    (queried_terminal_zero hm (by omega) ell D eps A hzero ht)

/-- The literal first-hitting time, with top for a trajectory that never
hits, is at least the complete chain length. -/
theorem queriedHittingTime_lower {m n : ℕ} (hm : 0 < m) (hn : 10 ≤ n)
    {ell D eps : ℝ} (hell : 0 < ell) (hD : 0 < D) (heps : 0 < eps)
    (hsize : (n : ℝ) ≤ constants.cD * (D / scale constants ell eps))
    {X : Set (Composite.Primal m)} {Y : Set (Composite.Dual m n)}
    (A : Oracle.DeterministicFOComponent X Y)
    (hmatch : A.MatchesInstance (ScaledMembership.scaled (by omega : 0 < n) ell D eps))
    (hzero : A.IsZeroRespectingOn (ScaledMembership.scaled (by omega : 0 < n) ell D eps)) :
    (m * (n + 3) : WithTop ℕ) ≤
      Oracle.queriedHittingTime A (ScaledMembership.scaled (by omega : 0 < n) ell D eps) ell eps := by
  apply le_of_not_gt
  intro hhit
  obtain ⟨t, ht, hstationary⟩ :=
    (Oracle.queriedHittingTime_lt_iff A (ScaledMembership.scaled (by omega : 0 < n) ell D eps)
      ell eps (m * (n + 3))).mp hhit
  exact hittingTimeAtLeast hm hn hell hD heps hsize A hmatch hzero t ht hstationary

/-- The concrete floor choice is admissible under exactly the current
manuscript's accuracy condition. -/
theorem floor_hittingTimeAtLeast {ell D Delta eps : ℝ}
    (hell : 0 < ell) (hD : 0 < D) (hDelta : 0 < Delta) (heps : 0 < eps)
    (hacc : eps ≤ c0 constants * min (ell * D) (Real.sqrt (ell * Delta))) :
    Oracle.ZeroRespectingHittingTimeAtLeast
      (ScaledMembership.scaled (m := stages constants ell Delta eps)
        (by have h := lengths_admissible constants hell hD hDelta heps hacc; exact lt_of_lt_of_le (by norm_num) h.2)
        ell D eps) ell eps
      (NCC.chainLength (stages constants ell Delta eps) (innerLength constants ell D eps)) := by
  have hadm := lengths_admissible constants hell hD hDelta heps hacc
  intro X Y A hmatch hzero
  exact hittingTimeAtLeast (lt_of_lt_of_le (by norm_num) hadm.1) hadm.2 hell hD heps
    (innerLength_le_raw constants hell hD heps) A hmatch hzero

/-- One literal current scaled instance simultaneously satisfies the
manuscript's class definition, the zero-respecting no-hit theorem, and the
displayed cubic-in-accuracy numerical horizon bound. -/
theorem current_zeroRespecting_lower {ell D Delta eps : ℝ}
    (hell : 0 < ell) (hD : 0 < D) (hDelta : 0 < Delta) (heps : 0 < eps)
    (hacc : eps ≤ c0 constants * min (ell * D) (Real.sqrt (ell * Delta))) :
    ∃ (m n : ℕ) (hn : 0 < n),
      NCC.Admissible m n ∧
      NCC.Model.WithinClass ell D Delta (ScaledMembership.scaled (m := m) hn ell D eps) ∧
      Oracle.ZeroRespectingHittingTimeAtLeast (ScaledMembership.scaled (m := m) hn ell D eps)
        ell eps (NCC.chainLength m n) ∧
      c1 constants * (ell ^ 2 * D * Delta / eps ^ 3) ≤ (NCC.chainLength m n : ℝ) := by
  have hadm := lengths_admissible constants hell hD hDelta heps hacc
  refine ⟨stages constants ell Delta eps, innerLength constants ell D eps,
    lt_of_lt_of_le (by norm_num) hadm.2,
    hadm, ?_, floor_hittingTimeAtLeast hell hD hDelta heps hacc,
    chain_length_lower constants hell hD hDelta heps hacc⟩
  exact ScaledMembership.withinClass (lt_of_lt_of_le (by norm_num) hadm.1) hadm.2 hell hD hDelta heps
    (ScaledMembership.floor_gap hell hDelta heps)

end

end NCC.Lower.ZeroRespecting
