name = "ncc_formalization"
version = "0.1.0"
defaultTargets = ["NCC", "NCCAudit"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "11d11a11a667a8fa8ea19d9456fe059f683e308f"

[[lean_lib]]
name = "NCC"

[[lean_lib]]
name = "NCPLVerification"
srcDir = "Legacy"
leanOptions = { autoImplicit = true, maxSynthPendingDepth = 3, weak.linter.unusedVariables = false, weak.linter.unusedSimpArgs = false, weak.linter.unusedSectionVars = false, weak.linter.unnecessarySeqFocus = false }

[[lean_lib]]
name = "NCCLowerBoundVerification"
srcDir = "Legacy"
leanOptions = { autoImplicit = true, maxSynthPendingDepth = 3, weak.linter.unusedVariables = false, weak.linter.unusedSimpArgs = false, weak.linter.unusedSectionVars = false, weak.linter.unnecessarySeqFocus = false }

[[lean_lib]]
name = "NCCLowerBound"
srcDir = "Legacy"
leanOptions = { autoImplicit = true, maxSynthPendingDepth = 3, weak.linter.unusedVariables = false, weak.linter.unusedSimpArgs = false, weak.linter.unusedSectionVars = false, weak.linter.unnecessarySeqFocus = false }

[[lean_lib]]
name = "NCCAudit"
roots = ["Audit.Axioms"]
